name: Build and Release

on:
  push:
    branches:
      - main

env:
  RELEASE_TAG: v$(date +'%Y%m%d-%H%M%S')

jobs:
  build:
    name: Build for macOS and Linux
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@v1

      - name: Install Dependencies
        run: deno cache --unstable deps.ts

      - name: Build and package
        run: |
          deno compile --unstable --target x86_64-apple-darwin --output dist/app-macos-x64 app.ts
          deno compile --unstable --target aarch64-apple-darwin --output dist/app-macos-arm64 app.ts
          deno compile --unstable --target x86_64-unknown-linux-gnu --output dist/app-linux-x64 app.ts

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-app
          path: dist/

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: Release ${{ env.RELEASE_TAG }}
          body: |
            Changes in this release:
            - Update dependency X to version Y
          draft: false
          prerelease: false

      - name: Upload macOS Intel asset
        uses: actions/upload-artifact@v2
        with:
          name: mac-intel
          path: dist/app-macos-x64

      - name: Upload macOS Apple Silicon asset
        uses: actions/upload-artifact@v2
        with:
          name: mac-arm64
          path: dist/app-macos-arm64

      - name: Upload Linux asset
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: dist/app-linux-x64

      - name: Attach assets to release
        id: attach_assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/app-${{ matrix.os }}
          asset_name: app-${{ matrix.os }}
          asset_content_type: application/octet-stream
