name: Build and Release

on:
  push:
    branches:
      - main

env:
  RELEASE_TAG: v$(date +'%Y%m%d-%H%M%S')

jobs:
  build:
    name: Build for macOS Apple Silicon
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macos-latest]
        arch: [arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.32.1

      - name: Build and package
        run: |
          deno compile --unstable --allow-env --allow-read --allow-write --target aarch64-apple-darwin --output dist/app-aarch64-apple-darwin main.ts

      - name: Upload artifact
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.RELEASE_UPLOAD_URL }}
          asset_path: dist/app-aarch64-apple-darwin
          asset_name: app-aarch64-apple-darwin
          asset_content_type: application/octet-stream

    env:
      ELECTRON_CACHE: macos-latest-electron-cache
      ELECTRON_BUILDER_CACHE: macos-latest-electron-builder-cache

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_UPLOAD_URL: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: Release ${{ env.RELEASE_TAG }}
          body: |
            Changes in this release:
            - Update dependency X to version Y
          draft: false
          prerelease: false

      - name: Set release upload URL
        id: set_release_upload_url
        run: echo "::set-output name=RELEASE_UPLOAD_URL::${{ steps.create_release.outputs.upload_url }}"
        shell: bash

      - name: Upload macOS Intel asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.release.outputs.RELEASE_UPLOAD_URL }}
          asset_path: dist/app-macos-x64
          asset_name: app-macos-x64
          asset_content_type: application/octet-stream

      - name: Upload macOS Apple Silicon asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.release.outputs.RELEASE_UPLOAD_URL }}
          asset_path: dist/app-macos-arm64
          asset_name: app-macos-arm64
          asset_content_type: application/octet-stream

      - name: Upload Linux Intel asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.release.outputs.RELEASE_UPLOAD_URL }}
          asset_path: dist/app-ubuntu-latest-x64
          asset_name: app-ubuntu-latest-x64
          asset_content_type: application/octet-stream

